// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; // Return web configuration instead of throwing an error
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBnwI2qJNDW3CVNdf1_NidUMUrYTepqAxg",
      authDomain: "saborly-397b6.firebaseapp.com",
      projectId: "saborly-397b6",
      storageBucket: "saborly-397b6.firebasestorage.app",
      messagingSenderId: "420029681993",
      appId: "1:420029681993:web:4c0228b4b3c3efe1d68a98",
      measurementId: "G-6EWPX5Z5J9");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB_sjOmiBU-9PLh4Mn5pscrUlnsw7NpUY',
    appId: '1:420029681993:android:a5cf60729f9758d0d68a98',
    messagingSenderId: '420029681993',
    projectId: 'saborly-397b6',
    storageBucket: 'saborly-397b6.firebasestorage.app',
  );
}
